sudo: false
language: node_js
node_js:
  - "8"
  - "10"
before_script:
  - greenkeeper-lockfile-update
before_install:
  - npm install -g greenkeeper-lockfile
after_script:
  - greenkeeper-lockfile-upload
