sudo: false
language: node_js
node_js:
  - "8"
  - "10"
before_script:
  - greenkeeper-lockfile-update
before_install:
  - yarn global add greenkeeper-lockfile@1
after_script:
  - greenkeeper-lockfile-upload
