sudo: false
language: node_js
node_js:
  - "8"
before_script:
# If this command fails and you can't fix it, file an issue and add an exception to .nsprc
  - npm run nsp-check
  - greenkeeper-lockfile-update
before_install:
  - yarn global add greenkeeper-lockfile@1
after_script:
  - greenkeeper-lockfile-upload
